#usr/bin/env python3

#import packages
import pandas as pd
import numpy as np

#prep the data
data = pd.read_csv("peak_ribozyme_sequences.tsv",sep='\t')
seqs = []
for i in range(len(data[",0"])-1):
    x = data[",0"][i].split(",")[1]
    y = x.rstrip(x[-1])
    z = y[:5] + "U" + y[5:]
    seqs.append(z)

p53_dbd_rna = "UGGCCGCUGAGCAGCAGCGUGCCGAGCCAGAAAACCUAUCAGGGCAGCUAUGGCUUUCGCCUGGGCUUUCUGCAUAGCGGCACCGCGAAAAGCGUGACCUGCACCUAUAGCCCGGCGCUGAACAAAAUGUUUUGCCAGCUGGCGAAAACCUGCCCGGUGCAGCUGUGGGUGGAUAGCACCCCGCCGCCGGGCACCCGCGUGCGCGCGAUGGCGAUUUAUAAACAGAGCCAGCAUAUGACCGAAGUGGUGCGCCGCUGCCCGCAUCAUGAACGCUGCAGCGAUAGCGAUGGCCUGGCGCCGCCGCAGCAUCUGAUUCGCGUGGAAGGCAACCUGCGCGUGGAAUAUCUGGAUGAUCGCAACACCUUUCGCCAUAGCGUGGUGGUGCCGUAUGAACCGCCGGAAGUGGGCAGCGAUUGCACCACCAUUCAUUAUAACUAUAUGUGCAACAGCAGCUGCAUGGGCGGCAUGAACCGCCGCCCGAUUCUGACCAUUAUUACCCUGGAAGAUAGCAGCGGCAACCUGCUGGGCCGCAACAGCUUUGAAGUGCGCGUGUGCGCGUGCCCGGGCCGCGAUCGCCGCACCGAAGAAGAAAACCUGCGCAAAAAAGGCGAACCGCAUCAUGAACUGCCG"

p53 = "GCGUGCGAUGAAUUUGGCCAUAUUAAACUGAUGAACCCGCAGCGCAGCACCGUGUGGUAUUAAAUGGAAGAACCGCAGAGCGAUCCGAGCGUGGAACCGCCGCUGAGCCAGGAAACCUUUAGCGAUCUGUGGAAACUGCUGCCGGAAAACAACGUGCUGAGCCCGCUGCCGAGCCAGGCGAUGGAUGAUCUGAUGCUGAGCCCGGAUGAUAUUGAACAGUGGUUUACCGAAGAUCCGGGCCCGGAUGAAGCGCCGCGCAUGCCGGAAGCGGCGCCGCCGGUGGCGCCGGCGCCGGCGGCGCCGACCCCGGCGGCGCCGGCGCCGGCGCCGAGCUGGCCGCUGAGCAGCAGCGUGCCGAGCCAGAAAACCUAUCAGGGCAGCUAUGGCUUUCGCCUGGGCUUUCUGCAUAGCGGCACCGCGAAAAGCGUGACCUGCACCUAUAGCCCGGCGCUGAACAAAAUGUUUUGCCAGCUGGCGAAAACCUGCCCGGUGCAGCUGUGGGUGGAUAGCACCCCGCCGCCGGGCACCCGCGUGCGCGCGAUGGCGAUUUAUAAACAGAGCCAGCAUAUGACCGAAGUGGUGCGCCGCUGCCCGCAUCAUGAACGCUGCAGCGAUAGCGAUGGCCUGGCGCCGCCGCAGCAUCUGAUUCGCGUGGAAGGCAACCUGCGCGUGGAAUAUCUGGAUGAUCGCAACACCUUUCGCCAUAGCGUGGUGGUGCCGUAUGAACCGCCGGAAGUGGGCAGCGAUUGCACCACCAUUCAUUAUAACUAUAUGUGCAACAGCAGCUGCAUGGGCGGCAUGAACCGCCGCCCGAUUCUGACCAUUAUUACCCUGGAAGAUAGCAGCGGCAACCUGCUGGGCCGCAACAGCUUUGAAGUGCGCGUGUGCGCGUGCCCGGGCCGCGAUCGCCGCACCGAAGAAGAAAACCUGCGCAAAAAAGGCGAACCGCAUCAUGAACUGCCGCCGGGCAGCACCAAACGCGCGCUGCCGAACAACACCAGCAGCAGCCCGCAGCCGAAAAAAAAACCGCUGGAUGGCGAAUAUUUUACCCUGCAGAUUCGCGGCCGCGAACGCUUUGAAAUGUUUCGCGAACUGAACGAAGCGCUGGAACUGAAAGAUGCGCAGGCGGGCAAAGAACCGGGCGGCAGCCGCGCGCAUAGCAGCCAUCUGAAAAGCAAAAAAGGCCAGAGCACCAGCCGCCAUAAAAAACUGAUGUUUAAAACCGAAGGCCCGGAUAGCGAU"

#import the alignment packages
import Bio
from Bio import pairwise2
from Bio.Seq import Seq

#note the pairwise2 is being removed, but given that I have very limited time and computing power, and it works for the time being, it will suffice

dbd_scores = []
scores= []
for seq in seqs:
        dbd_score = pairwise2.align.globalxx(p53_dbd_rna, seq, score_only = True)
        score = pairwise2.align.globalxx(p53, seq, score_only = True)
        dbd_scores.append(dbd_score)
        scores.append(score)
print("Done")

#save as csv
dbd_df = pd.DataFrame(dbd_scores)
dbd_df.to_csv("dbd_scores.csv", sep='\t')

df = pd.DataFrame(scores)
df.to_csv("full_alignment_scores.csv", sep = '\t')
