#usr/bin/env python3

#import packages
import pandas as pd
import numpy as np

#prep the data
data = pd.read_csv("peak_ribozyme_sequences.tsv",sep='\t')
seqs = []
for i in range(len(data[",0"])-1):
    x = data[",0"][i].split(",")[1]
    y = x.rstrip(x[-1])
    z = y[:5] + "U" + y[5:]
    seqs.append(z)

p53_dbd_rna = "UGGCCGCUGAGCAGCAGCGUGCCGAGCCAGAAAACCUAUCAGGGCAGCUAUGGCUUUCGCCUGGGCUUUCUGCAUAGCGGCACCGCGAAAAGCGUGACCUGCACCUAUAGCCCGGCGCUGAACAAAAUGUUUUGCCAGCUGGCGAAAACCUGCCCGGUGCAGCUGUGGGUGGAUAGCACCCCGCCGCCGGGCACCCGCGUGCGCGCGAUGGCGAUUUAUAAACAGAGCCAGCAUAUGACCGAAGUGGUGCGCCGCUGCCCGCAUCAUGAACGCUGCAGCGAUAGCGAUGGCCUGGCGCCGCCGCAGCAUCUGAUUCGCGUGGAAGGCAACCUGCGCGUGGAAUAUCUGGAUGAUCGCAACACCUUUCGCCAUAGCGUGGUGGUGCCGUAUGAACCGCCGGAAGUGGGCAGCGAUUGCACCACCAUUCAUUAUAACUAUAUGUGCAACAGCAGCUGCAUGGGCGGCAUGAACCGCCGCCCGAUUCUGACCAUUAUUACCCUGGAAGAUAGCAGCGGCAACCUGCUGGGCCGCAACAGCUUUGAAGUGCGCGUGUGCGCGUGCCCGGGCCGCGAUCGCCGCACCGAAGAAGAAAACCUGCGCAAAAAAGGCGAACCGCAUCAUGAACUGCCG"

p53 = "GCGUGCGAUGAAUUUGGCCAUAUUAAACUGAUGAACCCGCAGCGCAGCACCGUGUGGUAUUAAAUGGAAGAACCGCAGAGCGAUCCGAGCGUGGAACCGCCGCUGAGCCAGGAAACCUUUAGCGAUCUGUGGAAACUGCUGCCGGAAAACAACGUGCUGAGCCCGCUGCCGAGCCAGGCGAUGGAUGAUCUGAUGCUGAGCCCGGAUGAUAUUGAACAGUGGUUUACCGAAGAUCCGGGCCCGGAUGAAGCGCCGCGCAUGCCGGAAGCGGCGCCGCCGGUGGCGCCGGCGCCGGCGGCGCCGACCCCGGCGGCGCCGGCGCCGGCGCCGAGCUGGCCGCUGAGCAGCAGCGUGCCGAGCCAGAAAACCUAUCAGGGCAGCUAUGGCUUUCGCCUGGGCUUUCUGCAUAGCGGCACCGCGAAAAGCGUGACCUGCACCUAUAGCCCGGCGCUGAACAAAAUGUUUUGCCAGCUGGCGAAAACCUGCCCGGUGCAGCUGUGGGUGGAUAGCACCCCGCCGCCGGGCACCCGCGUGCGCGCGAUGGCGAUUUAUAAACAGAGCCAGCAUAUGACCGAAGUGGUGCGCCGCUGCCCGCAUCAUGAACGCUGCAGCGAUAGCGAUGGCCUGGCGCCGCCGCAGCAUCUGAUUCGCGUGGAAGGCAACCUGCGCGUGGAAUAUCUGGAUGAUCGCAACACCUUUCGCCAUAGCGUGGUGGUGCCGUAUGAACCGCCGGAAGUGGGCAGCGAUUGCACCACCAUUCAUUAUAACUAUAUGUGCAACAGCAGCUGCAUGGGCGGCAUGAACCGCCGCCCGAUUCUGACCAUUAUUACCCUGGAAGAUAGCAGCGGCAACCUGCUGGGCCGCAACAGCUUUGAAGUGCGCGUGUGCGCGUGCCCGGGCCGCGAUCGCCGCACCGAAGAAGAAAACCUGCGCAAAAAAGGCGAACCGCAUCAUGAACUGCCGCCGGGCAGCACCAAACGCGCGCUGCCGAACAACACCAGCAGCAGCCCGCAGCCGAAAAAAAAACCGCUGGAUGGCGAAUAUUUUACCCUGCAGAUUCGCGGCCGCGAACGCUUUGAAAUGUUUCGCGAACUGAACGAAGCGCUGGAACUGAAAGAUGCGCAGGCGGGCAAAGAACCGGGCGGCAGCCGCGCGCAUAGCAGCCAUCUGAAAAGCAAAAAAGGCCAGAGCACCAGCCGCCAUAAAAAACUGAUGUUUAAAACCGAAGGCCCGGAUAGCGAU"

#import the alignment packages
import Bio
from Bio import pairwise2
from Bio.Seq import Seq 

#note the pairwise2 is being removed, but given that I have very limited time and computing power, and it works for the time being, it will suffice

alignments_dbd = []
alignment = []
for seq in seqs:
	alignment_dbd = pairwise2.align.localds(p53_dbd_rna, seq, blosum62, -10, -1)
	alignment = pairwise2.align.localds(p53, seq, blosum62, -10, -1)
	alignments_dbd.append(alignment_dbd)
	alignments.append(alignment)
print("Done")

#save as csv
dbd_df = pd.DataFrame(alignments_dbd)
dbd_df.to_csv("dbd_alignments.csv", sep='\t')

df = pd.DataFrame(alignments)
df.to_csv("alignments.csv", sep = '\t')

